<a href="https://colab.research.google.com/github/abdoulahat/Learn_Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ce document est en cours. Je vais donner les détails de chacun des points. Merci pour votre compréhension. 

##  **Python Numpy**
### **1. Create a Numpy Array from list, tuple or list of lists using numpy.array()**

In [0]:
import numpy as np

**Create Numpy Array from a list**

In [0]:
npArray = np.array([1,2,3,4,5,6,7,8,9])
print(f"Contents of th npArray : \n{npArray}")

Contents of th npArray : 
[1 2 3 4 5 6 7 8 9]


**Create Numpy Array from a tuple**

In [0]:
npArray = np.array((11,22,33,44,55,66,77,88))
print(f"Contents of th npArray : \n{npArray}")

Contents of th npArray : 
[11 22 33 44 55 66 77 88]


**Check type of Numpy Array object**

In [0]:
print(f"type of the npArray : \n{type(npArray)}")

type of the npArray : 
<class 'numpy.ndarray'>


**Check the data type of elements in Numpy Array**

In [0]:
print(f"Data Type of elements in  ndArray : \n{npArray.dtype}")

Data Type of elements in  ndArray : 
int64


**Create 2D Numpy Array from a list of list**

In [0]:
npArray = np.array([[77, 88, 34], [20, 21, 35], [12, 16, 90]])
print(f"Contents of the npAray : \n{npArray}")

Contents of the npAray : 
[[77 88 34]
 [20 21 35]
 [12 16 90]]


**Create 1D Numpy Array from list of list : list comprehension**

In [0]:
listOfLists = [[77, 88, 99], [31, 42, 63], [11, 22, 33]]
npArray = np.array([num for elem in listOfLists for num in elem])
print(f"Contents of the npAray : \n{npArray}")

Contents of the npAray : 
[77 88 99 31 42 63 11 22 33]


**Create a Numpy Array from a list with different data type**

In [0]:
npArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9] , dtype=float)
print(f"Contents of the npAray : \n{npArray}\n\n Type of the ndArray : \n{type(npArray)}\n\n Data Type of elements in  ndArray : \n{npArray.dtype}")

Contents of the npAray : 
[1. 2. 3. 4. 5. 6. 7. 8. 9.]

 Type of the ndArray : 
<class 'numpy.ndarray'>

 Data Type of elements in  ndArray : 
float64


**Complete example is as follows,**

In [0]:
def main():
  print('*** Create a ndArray from a list or tuple ***')
  # Create ndArray from a list
  npArray = np.array([1,2,3,4,5,6,7,8,9])
  print(f'\nContents of the ndArray : {npArray}')
  # Create ndArray from a tuple
  npArray = np.array( (11,22,33,44,55,66,77,88 ) )
  print(f'\nContents of the ndArray : {npArray}')
  print(f'\nType Created  ndArray : {type(npArray)}')
  print(f'\nData Type of elements in  ndArray : {npArray.dtype}')
  print(f'\n*** Create a 2D ndArray from a list of lists ***\n')
  # Create 2D ndarray form list of list
  npArray = np.array( [ [77, 88, 99] , [31,42,63] , [11,22,33]])
  print(f'Contents of the ndArray : \n{npArray}')
  print('\n*** Create one dimension ndArray from a list of lists ***')
  listOfLists = [[77, 88, 99], [31, 42, 63], [11, 22, 33]]
  # Create one dimension ndArray from a list of lists
  npArray = np.array([ elem for singleList in listOfLists for elem in singleList])
  print(f'\nContents of the ndArray : {npArray}')
  print('\n*** Create a ndArray from a list with different data type ***\n')
  # Create ndArray of float datatype from a list of int
  npArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9] , dtype=float)
  print('Contents of the ndArray : ', npArray)
  print('Type of the ndArray : ', npArray.dtype)
if __name__ == '__main__':
  main()

*** Create a ndArray from a list or tuple ***

Contents of the ndArray : [1 2 3 4 5 6 7 8 9]

Contents of the ndArray : [11 22 33 44 55 66 77 88]

Type Created  ndArray : <class 'numpy.ndarray'>

Data Type of elements in  ndArray : int64

*** Create a 2D ndArray from a list of lists ***

Contents of the ndArray : 
[[77 88 99]
 [31 42 63]
 [11 22 33]]

*** Create one dimension ndArray from a list of lists ***

Contents of the ndArray : [77 88 99 31 42 63 11 22 33]

*** Create a ndArray from a list with different data type ***

Contents of the ndArray :  [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Type of the ndArray :  float64


### **2. Find the index of value in Numpy Array using numpy.where()**

In [0]:
# Create a numpy array from a list of numbers
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])

In [0]:
# Get the index of elements with value 15
result = np.where(arr == 15)
print('Tuple of arrays returned : ', result)
print("Elements with value 15 exists at following indices", result[0], sep='\n')

Tuple of arrays returned :  (array([ 4,  7, 11]),)
Elements with value 15 exists at following indices
[ 4  7 11]


In [0]:
	
result[0][0]

4

In [0]:
boolArr = (arr == 15)
boolArr

array([False, False, False, False,  True, False, False,  True, False,
       False, False,  True, False, False])

In [0]:
result = np.where(boolArr)

**Find index of a value in 2D Numpy array | Matrix**

In [0]:
# Create a 2D Numpy array from list of lists
arr = np.array([[11, 12, 13], [14, 15, 16], [17, 15, 11], [12, 14, 15]])
result = np.where(arr == 15)
print('Tuple of arrays returned : ', result)

Tuple of arrays returned :  (array([1, 2, 3]), array([1, 1, 2]))


- Now returned array 1 represents the row indices where this value is found i.e. [1, 2, 3]
- Whereas, array 2 represents the column indices where this value is found i.e. [1, 1, 2]

In [0]:
# zip the 2 arrays to get the exact coordinates
listOfCoordinates= list(zip(result[0], result[1]))
for cord in listOfCoordinates:
    print(cord)

(1, 1)
(2, 1)
(3, 2)


**Get indices of elements based on multiple conditions**

In [0]:
# Create a numpy array from a list of numbers
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
 
# Get the index of elements with value less than 16 and greater than 12
result = np.where((arr > 12) & (arr < 16))
print("Elements with value less than 16 and greater than 12 exists at following indices:", result, sep='\n')

Elements with value less than 16 and greater than 12 exists at following indices:
(array([ 2,  3,  4,  7, 10, 11]),)


In [0]:
result = np.where(arr == 15)
if len(result) > 0 and len(result[0]) > 0:
  print('First Index of element with value 15 is ', result[0][0])

First Index of element with value 15 is  4


**Complete example is as follows,**

In [0]:
def main():
    print("*** Find the index of an element in 1D Numpy Array ***\n")
 
    # Create a numpy array from a list of numbers
    arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
 
    # Get the index of elements with value 15
    result = np.where(arr == 15)
 
    print('Tuple of arrays returned : ', result)
    print("Elements with value 15 exists at following indices", result[0], sep='\n')
    print('First Index of element with value 15 is : ', result[0][0])
 
    # If given element doesn't exist in the array then it will return an empty array
    result = np.where(arr == 111)
    print('Empty Array returned : ', result)
    print("value 111 exists at following indices", result[0], sep='\n')
 
    print("\n*** Find the index of an element in 2D Numpy Array ***\n")
 
    # Create a 2D Numpy array from list of lists
    arr = np.array([[11, 12, 13],
                    [14, 15, 16],
                    [17, 15, 11],
                    [12, 14, 15]])
 
    print('Contents of 2D Numpy Array', arr, sep='\n')
 
    # Get the index of elements with value 17
    result = np.where(arr == 15)
 
    print('Tuple of arrays returned : ', result)
 
    print('List of coordinates where element with value 15 exists in given 2D array : ')
    # zip the 2 arrays to get the exact coordinates
    listOfCoordinates = list(zip(result[0], result[1]))
    # iterate over the list of coordinates
    for cord in listOfCoordinates:
        print(cord)
 
    print("\n*** Get the index of an element based on multiple conditions Numpy Array ***\n")
 
    # Create a numpy array from a list of numbers
    arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
 
    # Get the index of elements with value less than 16 and greater than 12
    result = np.where((arr > 12) & (arr < 16))
    print("Elements with value less than 16 and greater than 12 exists at following indices", result, sep='\n')
 
    print("\n*** Get the first index of an element in Numpy Array ***")
 
    result = np.where(arr == 15)
    if len(result) > 0 and len(result[0]) > 0:
        print('First Index of element with value 15 is ', result[0][0])
 
 
if __name__ == '__main__':
    main()

*** Find the index of an element in 1D Numpy Array ***

Tuple of arrays returned :  (array([ 4,  7, 11]),)
Elements with value 15 exists at following indices
[ 4  7 11]
First Index of element with value 15 is :  4
Empty Array returned :  (array([], dtype=int64),)
value 111 exists at following indices
[]

*** Find the index of an element in 2D Numpy Array ***

Contents of 2D Numpy Array
[[11 12 13]
 [14 15 16]
 [17 15 11]
 [12 14 15]]
Tuple of arrays returned :  (array([1, 2, 3]), array([1, 1, 2]))
List of coordinates where element with value 15 exists in given 2D array : 
(1, 1)
(2, 1)
(3, 2)

*** Get the index of an element based on multiple conditions Numpy Array ***

Elements with value less than 16 and greater than 12 exists at following indices
(array([ 2,  3,  4,  7, 10, 11]),)

*** Get the first index of an element in Numpy Array ***
First Index of element with value 15 is  4


### **3. Select an element or sub array by index from a Numpy Array**

In [0]:
# Create a numpy ndArray
npArray = np.arange(1, 20, 2)
print(npArray)
# Select an element at index 2 (Index starts from 0)
elem = npArray[2]
print('Element at 2nd index  : ' , elem)


[ 1  3  5  7  9 11 13 15 17 19]
Element at 2nd index  :  5


**Select a sub array from Numpy Array by index range**

In [0]:
# Select elements from index 1 to 6
subArray = npArray[1:7]
subArray

array([ 3,  5,  7,  9, 11, 13])

**Complete example is as follows,**

In [0]:
def main():
 
   # Create a numpy ndArray
   npArray = np.arange(1, 20, 2)
 
   print('Contents of numpy ndArray', npArray)
 
   print('\n*** Select an element by Index ***\n')
   # Select an element at index 2 (Index starts from 0)
   elem = npArray[2]
   print('Element at 2nd index  : ' , elem)
 
   print('\n*** Select a by sub array by Index Range ***\n')
   # Select elements from index 1 to 6
   subArray = npArray[1:7]
   print('Sub Array from 1st to 6th index are :', subArray)
   # Select elements from beginning to index 3
   subArray = npArray[:4]
   print('Sub Array from beginning to 3rd index are :', subArray)
 
   # Select elements from 2nd index to end
   subArray = npArray[2:]
   print('Sub Array from 2nd index to end are :', subArray)
 
 
   print('\n*** Sub Array is just a View not the copy ***\n')
   npArray = np.arange(1, 20, 2)
   print('Contents of Original Array : ', subArray)
 
   # Select a sub array of elements from index 1 to 6
   subArray = npArray[1:7]
   print('Contents of Sub Array : ', subArray)
   # Change contents of sub array
   subArray[1] = 220
   '''
   Sub array is just a view of original array i.e. data is not copied just a view of sub array is created.
   Any modification in it will be reflected in original nodArray too
   '''
   print('Contents of modified Sub Array : ', subArray)
   print('Contents of Original Array : ', npArray)
 
 
   print('\n*** Create a copy of Sub Array of ndArray ***\n')
   npArray = np.arange(1, 20, 2)
   print('Contents of Original Array : ', subArray)
   # Fetch a copy of sub array from index 1 to 6
   subArray = npArray[1:7].copy()
   print('Contents of Sub Array : ', subArray)
 
   # Change contents of sub array
   subArray[1] = 220
 
   '''
   As subArray is a copy of sub array not the view only, so changes made in it will not be reflected in main array.
   '''
   print('Contents of modified Sub Array : ', subArray)
   print('Contents of Original Array : ', npArray)
 
 
if __name__ == '__main__':
   main()

Contents of numpy ndArray [ 1  3  5  7  9 11 13 15 17 19]

*** Select an element by Index ***

Element at 2nd index  :  5

*** Select a by sub array by Index Range ***

Sub Array from 1st to 6th index are : [ 3  5  7  9 11 13]
Sub Array from beginning to 3rd index are : [1 3 5 7]
Sub Array from 2nd index to end are : [ 5  7  9 11 13 15 17 19]

*** Sub Array is just a View not the copy ***

Contents of Original Array :  [ 5  7  9 11 13 15 17 19]
Contents of Sub Array :  [ 3  5  7  9 11 13]
Contents of modified Sub Array :  [  3 220   7   9  11  13]
Contents of Original Array :  [  1   3 220   7   9  11  13  15  17  19]

*** Create a copy of Sub Array of ndArray ***

Contents of Original Array :  [  3 220   7   9  11  13]
Contents of Sub Array :  [ 3  5  7  9 11 13]
Contents of modified Sub Array :  [  3 220   7   9  11  13]
Contents of Original Array :  [ 1  3  5  7  9 11 13 15 17 19]


### **4. Select rows / columns by index from a 2D Numpy Array | Multi Dimension**</font>

In [0]:
# Create a 2D Numpy adArray with 3 rows & 3 columns | Matrix
nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
nArr2D

array([[21, 22, 23],
       [11, 22, 33],
       [43, 77, 89]])

**Select a single element from 2D Numpy Array by index**

In [0]:
# Select element at row index 1 & column index 2
num = nArr2D[1][2]
print('element at row index 1 & column index 2 is : ' , num)

element at row index 1 & column index 2 is :  33


**Select Rows by Index from a 2D Numpy Array**

In [0]:
# Select a Row at index 1
row = nArr2D[1]
print('Contents of Row at Index 1 : ' , row)

Contents of Row at Index 1 :  [11 22 33]


In [0]:
# Select multiple rows from index 1 to 2
rows = nArr2D[1:3, :]
print(f'Rows from Index 1 to 2 : \n{rows}')

Rows from Index 1 to 2 : 
[[11 22 33]
 [43 77 89]]


**Select Columns by Index from a 2D Numpy Array**

In [0]:
columns = nArr2D[: , 1:3]
 
print(f'Column from Index 1 to 2 : \n{columns}')

Column from Index 1 to 2 : 
[[22 23]
 [22 33]
 [77 89]]


**Select a Sub Matrix or 2d Numpy Array from another 2D Numpy Array**

In [0]:
# Select a sub 2D array from row indices 1 to 2 & column indices 1 to 2
sub2DArr = nArr2D[1:3, 1:3]
print(f'Sub 2d Array : \n{sub2DArr}')

Sub 2d Array : 
[[22 33]
 [77 89]]


**Selected Row or Column or Sub Array is View only**

In [0]:
# Select row at index 1 from 2D array
row = nArr2D[1]
row[:] = 100
row

array([100, 100, 100])

**Complete example is as follows,**

In [0]:
def main():

   # Create a 2D Numpy adArray with 3 rows & 3 columns | Matrix
   nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
   print('Contents of 2D Array : {nArr2D}')
 
   print('\n*** Select an element by index from a 2D ndArray\n***')
   # Select element at row index 1 & column index 2
   num = nArr2D[1][2]
   print('element at row index 1 & column index 2 is : ' , num)
   # Another way to select element at row index 1 & column index 2
   num = nArr2D[1, 2]
   print('element at row index 1 & column index 2 is : ', num)
 
   print('\n*** Select Rows by Index from a 2D ndArray ***\n')
   # Select a Row at index 1
   row = nArr2D[1]
   print('Contents of Row at Index 1 : ' , row)
   # Select multiple rows from index 1 to 2
   rows = nArr2D[1:3, :]
   print('Rows from Index 1 to 2 :', rows)
   # Select multiple rows from index 1 to last index
   rows = nArr2D[1: , :]
   print('Rows from Index 1 to last row :')
   print(rows)
 
   print('\n*** Select Columns by Index from a 2D ndArray ***\n')
   # Select a column at index 1
   column = nArr2D[:, 1]
   print('Contents of Column at Index 1 : ', column)
   # Select multiple columns from index 1 to 2
   columns = nArr2D[: , 1:3]
   print('Column from Index 1 to 2 :')
   print(columns)
   # Select multiple columns from index 1 to last index
   columns = nArr2D[:, 1:]
   print('Column from Index 1 to last index :')
   print(columns)
 
   print('\n*** Select a Sub Matrix or 2d Array from another 2D ndArray ***\n')
   print('Original ndArray', nArr2D)
   # Select a sub 2D array from row indices 1 to 2 & column indices 1 to 2
   sub2DArr = nArr2D[1:3, 1:3] 
   print('Sub 2d Array :', sub2DArr)

   print('\n*** Sub Array is View only ***\n')
   print('Original ndArray', nArr2D)
   # Select row at index 1 from 2D array
   row = nArr2D[1]
   print('Contents of row / sub array', row)
   # Change all the elements in selected sub array to 100
   row[:] = 100
 
   # As sub array is a copy so, changes in it will be reflected in original array too
 
   print('Contents of modified row / sub array')
   print(row)
   print('Original ndArray')
   print(nArr2D)
 
   print('\n*** Fetching a copy of 2D Sub Array from 2D ndArray ***\n')
   # Create a 2D Numpy adArray with3 rows & columns | Matrix
   nArr2D = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
   # Select a copy of row at index 1 from 2D array
   row = nArr2D[1].copy()
   # Set all the elements in selected sub array to 100
   row[:] = 100
   '''
   Here sub array is a copy of original array so, modifying it will not affect the original ndArray
   '''
 
   print('Contents of modified row / sub array', row)
   print('Original ndArray', nArr2D)
 
if __name__ == '__main__':
   main()

Contents of 2D Array : {nArr2D}

*** Select an element by index from a 2D ndArray
***
element at row index 1 & column index 2 is :  33
element at row index 1 & column index 2 is :  33

*** Select Rows by Index from a 2D ndArray ***

Contents of Row at Index 1 :  [11 22 33]
Rows from Index 1 to 2 : [[11 22 33]
 [43 77 89]]
Rows from Index 1 to last row :
[[11 22 33]
 [43 77 89]]

*** Select Columns by Index from a 2D ndArray ***

Contents of Column at Index 1 :  [22 22 77]
Column from Index 1 to 2 :
[[22 23]
 [22 33]
 [77 89]]
Column from Index 1 to last index :
[[22 23]
 [22 33]
 [77 89]]

*** Select a Sub Matrix or 2d Array from another 2D ndArray ***

Original ndArray [[21 22 23]
 [11 22 33]
 [43 77 89]]
Sub 2d Array : [[22 33]
 [77 89]]

*** Sub Array is View only ***

Original ndArray [[21 22 23]
 [11 22 33]
 [43 77 89]]
Contents of row / sub array [11 22 33]
Contents of modified row / sub array
[100 100 100]ERROR! Session/line number was not unique in database. History logging mov

### **5. Select elements or indices by conditions from Numpy Array**</font>